In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
users_db = pd.read_csv('./users-processed.csv')
users_db.drop('Unnamed: 0', axis = 1)

USER_ID  GENDER  AGE  K_12_STUDENT  ACADEMIC_EDUCATOR  ARTIST  \
0           1       1    1             1                  0       0   
1           2       0   56             0                  0       0   
2           3       0   25             0                  0       0   
3           4       0   45             0                  0       0   
4           5       0   25             0                  0       0   
...       ...     ...  ...           ...                ...     ...   
6035     6036       1   25             0                  0       0   
6036     6037       1   45             0                  1       0   
6037     6038       1   56             0                  1       0   
6038     6039       1   45             0                  0       0   
6039     6040       0   25             0                  0       0   

      CLERICAL_ADMIN  COLLEGE_GRAD_STUDENT  CUSTOMER_SERVICE  \
0                  0                     0                 0   
1                  0                     0                 0   
2                  0                     0                 0   
3                  0                     0                 0   
4                  0                     0                 0   
...              ...                   ...               ...   
6035               0                     0                 0   
6036               0                     0                 0   
6037               0                     0                 0   
6038               0                     0                 0   
6039               0                     0                 0   

      DOCTOR_HEALTH_CARE  ...  OTHER_OR_NOT_SPECIFIED  PROGRAMMER  RETIRED  \
0                      0  ...                       0           0        0   
1                      0  ...                       0           0        0   
2                      0  ...                       0           0        0   
3                      0  ...                       0           0        0   
4                      0  ...                       0           0        0   
...                  ...  ...                     ...         ...      ...   
6035                   0  ...                       0           0        0   
6036                   0  ...                       0           0        0   
6037                   0  ...                       0           0        0   
6038                   0  ...                       1           0        0   
6039                   1  ...                       0           0        0   

      SALES_MARKETING  SCIENTIST  SELF_EMPLOYED  TECHNICIAN_ENGINEER  \
0                   0          0              0                    0   
1                   0          0              1                    0   
2                   0          1              0                    0   
3                   0          0              0                    0   
4                   0          0              0                    0   
...               ...        ...            ...                  ...   
6035                0          1              0                    0   
6036                0          0              0                    0   
6037                0          0              0                    0   
6038                0          0              0                    0   
6039                0          0              0                    0   

      TRADESMAN_CRAFTSMAN  UNEMPLOYED  WRITER  
0                       0           0       0  
1                       0           0       0  
2                       0           0       0  
3                       0           0       0  
4                       0           0       1  
...                   ...         ...     ...  
6035                    0           0       0  
6036                    0           0       0  
6037                    0           0       0  
6038                    0           0       0  
6039                    0           0       0  

[6040

In [5]:
users_db


Unnamed: 0  USER_ID  GENDER  AGE  K_12_STUDENT  ACADEMIC_EDUCATOR  \
0              0        1       1    1             1                  0   
1              1        2       0   56             0                  0   
2              2        3       0   25             0                  0   
3              3        4       0   45             0                  0   
4              4        5       0   25             0                  0   
...          ...      ...     ...  ...           ...                ...   
6035        6035     6036       1   25             0                  0   
6036        6036     6037       1   45             0                  1   
6037        6037     6038       1   56             0                  1   
6038        6038     6039       1   45             0                  0   
6039        6039     6040       0   25             0                  0   

      ARTIST  CLERICAL_ADMIN  COLLEGE_GRAD_STUDENT  CUSTOMER_SERVICE  ...  \
0          0               0                     0                 0  ...   
1          0               0                     0                 0  ...   
2          0               0                     0                 0  ...   
3          0               0                     0                 0  ...   
4          0               0                     0                 0  ...   
...      ...             ...                   ...               ...  ...   
6035       0               0                     0                 0  ...   
6036       0               0                     0                 0  ...   
6037       0               0                     0                 0  ...   
6038       0               0                     0                 0  ...   
6039       0               0                     0                 0  ...   

      OTHER_OR_NOT_SPECIFIED  PROGRAMMER  RETIRED  SALES_MARKETING  SCIENTIST  \
0                          0           0        0                0          0   
1                          0           0        0                0          0   
2                          0           0        0                0          1   
3                          0           0        0                0          0   
4                          0           0        0                0          0   
...                      ...         ...      ...              ...        ...   
6035                       0           0        0                0          1   
6036                       0           0        0                0          0   
6037                       0           0        0                0          0   
6038                       1           0        0                0          0   
6039                       0           0        0                0          0   

      SELF_EMPLOYED  TECHNICIAN_ENGINEER  TRADESMAN_CRAFTSMAN  UNEMPLOYED  \
0                 0                    0                    0           0   
1                 1                    0                    0           0   
2                 0                    0                    0           0   
3                 0                    0                    0           0   
4                 0                    0                    0           0   
...             ...                  ...                  ...         ...   
6035              0                    0                    0           0   
6036              0                    0                    0           0   
6037              0                    0                    0           0   
6038              0                    0                    0           0   
6039              0                    0                    0           0   

      WRITER  
0          0  
1          0  
2          0  
3          0  
4          1  
...      ...  
6035       0  
6036       0  
6037       0  
6038       0  
6039       0  

[6040 rows x 25 columns]

In [6]:
users_db.columns


Index(['Unnamed: 0', 'USER_ID', 'GENDER', 'AGE', 'K_12_STUDENT',
       'ACADEMIC_EDUCATOR', 'ARTIST', 'CLERICAL_ADMIN', 'COLLEGE_GRAD_STUDENT',
       'CUSTOMER_SERVICE', 'DOCTOR_HEALTH_CARE', 'EXECUTIVE_MANAGERIAL',
       'FARMER', 'HOMEMAKER', 'LAWYER', 'OTHER_OR_NOT_SPECIFIED', 'PROGRAMMER',
       'RETIRED', 'SALES_MARKETING', 'SCIENTIST', 'SELF_EMPLOYED',
       'TECHNICIAN_ENGINEER', 'TRADESMAN_CRAFTSMAN', 'UNEMPLOYED', 'WRITER'],
      dtype='object')

In [7]:
# copy the data
df_min_max_scaled = users_db.copy()
  
# apply normalization techniques by Column 1
column = 'AGE'
df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())    
  
# view normalized data
users_db = df_min_max_scaled
display(users_db)

Unnamed: 0  USER_ID  GENDER       AGE  K_12_STUDENT  ACADEMIC_EDUCATOR  \
0              0        1       1  0.000000             1                  0   
1              1        2       0  1.000000             0                  0   
2              2        3       0  0.436364             0                  0   
3              3        4       0  0.800000             0                  0   
4              4        5       0  0.436364             0                  0   
...          ...      ...     ...       ...           ...                ...   
6035        6035     6036       1  0.436364             0                  0   
6036        6036     6037       1  0.800000             0                  1   
6037        6037     6038       1  1.000000             0                  1   
6038        6038     6039       1  0.800000             0                  0   
6039        6039     6040       0  0.436364             0                  0   

      ARTIST  CLERICAL_ADMIN  COLLEGE_GRAD_STUDENT  CUSTOMER_SERVICE  ...  \
0          0               0                     0                 0  ...   
1          0               0                     0                 0  ...   
2          0               0                     0                 0  ...   
3          0               0                     0                 0  ...   
4          0               0                     0                 0  ...   
...      ...             ...                   ...               ...  ...   
6035       0               0                     0                 0  ...   
6036       0               0                     0                 0  ...   
6037       0               0                     0                 0  ...   
6038       0               0                     0                 0  ...   
6039       0               0                     0                 0  ...   

      OTHER_OR_NOT_SPECIFIED  PROGRAMMER  RETIRED  SALES_MARKETING  SCIENTIST  \
0                          0           0        0                0          0   
1                          0           0        0                0          0   
2                          0           0        0                0          1   
3                          0           0        0                0          0   
4                          0           0        0                0          0   
...                      ...         ...      ...              ...        ...   
6035                       0           0        0                0          1   
6036                       0           0        0                0          0   
6037                       0           0        0                0          0   
6038                       1           0        0                0          0   
6039                       0           0        0                0          0   

      SELF_EMPLOYED  TECHNICIAN_ENGINEER  TRADESMAN_CRAFTSMAN  UNEMPLOYED  \
0                 0                    0                    0           0   
1                 1                    0                    0           0   
2                 0                    0                    0           0   
3                 0                    0                    0           0   
4                 0                    0                    0           0   
...             ...                  ...                  ...         ...   
6035              0                    0                    0           0   
6036              0                    0                    0           0   
6037              0                    0                    0           0   
6038              0                    0                    0           0   
6039              0                    0                    0           0   

      WRITER  
0          0  
1          0  
2          0  
3          0  
4          1  
...      ...  
6035       0  
6036       0  
6037       0  
6038       0  
6039       0  

[6040 rows x 25 columns]

In [28]:
users_db.shape

(6040, 25)

In [8]:
df_min_max_scaled[column].max()

1.0

In [9]:
users_knn_df = users_db.drop(['Unnamed: 0', 'USER_ID'], axis = 1)

In [29]:
users_knn_df

GENDER       AGE  K_12_STUDENT  ACADEMIC_EDUCATOR  ARTIST  \
0          1  0.000000             1                  0       0   
1          0  1.000000             0                  0       0   
2          0  0.436364             0                  0       0   
3          0  0.800000             0                  0       0   
4          0  0.436364             0                  0       0   
...      ...       ...           ...                ...     ...   
6035       1  0.436364             0                  0       0   
6036       1  0.800000             0                  1       0   
6037       1  1.000000             0                  1       0   
6038       1  0.800000             0                  0       0   
6039       0  0.436364             0                  0       0   

      CLERICAL_ADMIN  COLLEGE_GRAD_STUDENT  CUSTOMER_SERVICE  \
0                  0                     0                 0   
1                  0                     0                 0   
2                  0                     0                 0   
3                  0                     0                 0   
4                  0                     0                 0   
...              ...                   ...               ...   
6035               0                     0                 0   
6036               0                     0                 0   
6037               0                     0                 0   
6038               0                     0                 0   
6039               0                     0                 0   

      DOCTOR_HEALTH_CARE  EXECUTIVE_MANAGERIAL  ...  OTHER_OR_NOT_SPECIFIED  \
0                      0                     0  ...                       0   
1                      0                     0  ...                       0   
2                      0                     0  ...                       0   
3                      0                     1  ...                       0   
4                      0                     0  ...                       0   
...                  ...                   ...  ...                     ...   
6035                   0                     0  ...                       0   
6036                   0                     0  ...                       0   
6037                   0                     0  ...                       0   
6038                   0                     0  ...                       1   
6039                   1                     0  ...                       0   

      PROGRAMMER  RETIRED  SALES_MARKETING  SCIENTIST  SELF_EMPLOYED  \
0              0        0                0          0              0   
1              0        0                0          0              1   
2              0        0                0          1              0   
3              0        0                0          0              0   
4              0        0                0          0              0   
...          ...      ...              ...        ...            ...   
6035           0        0                0          1              0   
6036           0        0                0          0              0   
6037           0        0                0          0              0   
6038           0        0                0          0              0   
6039           0        0                0          0              0   

      TECHNICIAN_ENGINEER  TRADESMAN_CRAFTSMAN  UNEMPLOYED  WRITER  
0                       0                    0           0       0  
1                       0                    0           0       0  
2                       0                    0           0       0  
3                       0                    0           0       0  
4                       0                    0           0       1  
...                   ...                  ...         ...     ...  
6035                    0                    0           0       0  
6036                    0                    0           0       0

In [11]:
users_knn_df.columns




Index(['GENDER', 'AGE', 'K_12_STUDENT', 'ACADEMIC_EDUCATOR', 'ARTIST',
       'CLERICAL_ADMIN', 'COLLEGE_GRAD_STUDENT', 'CUSTOMER_SERVICE',
       'DOCTOR_HEALTH_CARE', 'EXECUTIVE_MANAGERIAL', 'FARMER', 'HOMEMAKER',
       'LAWYER', 'OTHER_OR_NOT_SPECIFIED', 'PROGRAMMER', 'RETIRED',
       'SALES_MARKETING', 'SCIENTIST', 'SELF_EMPLOYED', 'TECHNICIAN_ENGINEER',
       'TRADESMAN_CRAFTSMAN', 'UNEMPLOYED', 'WRITER'],
      dtype='object')

In [12]:
users_knn = users_knn_df.to_numpy()

In [13]:
users_knn

array([[1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.43636364, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.43636364, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [30]:
from sklearn.neighbors import NearestNeighbors



knn = NearestNeighbors(algorithm='auto', leaf_size=30, n_neighbors=1, p=2)

knn.fit(users_knn)

NearestNeighbors(n_neighbors=1)

In [37]:
x_1 = knn.kneighbors([[1., 0.0001, 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]], return_distance=False)

In [41]:
int(x_1[0])+1

1

In [42]:
users_knn[0]

array([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [43]:
user_id = knn.kneighbors([users_knn[1000]], return_distance=True)[1]+1

In [44]:
user_id

array([[48]])

In [45]:
np.array_equal(users_knn[1000], users_knn[47])                                             

True

In [46]:
type(knn)

sklearn.neighbors._unsupervised.NearestNeighbors

In [52]:
import pickle
file_name = "knn_model_b1.pickle"
file_to_store = open(file_name, "wb")
pickle.dump(knn, file_to_store)
file_to_store.close()

In [53]:
knn_model_bytes = open(file_name, "rb")

In [54]:
knn_model = pickle.load(knn_model_bytes)


knn_model_bytes.close()
print(knn_model)

NearestNeighbors(n_neighbors=1)


In [57]:
int(x_1[0])+1

knn_model.kneighbors([users_knn[1]], return_distance=False)

array([[1]])

In [56]:
user_input = users_knn[3000]

In [25]:
user_input

array([0.        , 0.30909091, 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])